// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpellItBackend.Models;

namespace SpellItBackend.Migrations
{
    [DbContext(typeof(WordsContext))]
    [Migration("20220313163730_DbInitializationWithSeed")]
    partial class DbInitializationWithSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpellItBackend.Models.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("WordListId")
                        .HasColumnType("int");

                    b.Property<string>("WordName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WordId");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            WordId = 1,
                            WordListId = 1,
                            WordName = "avacado"
                        });
                });

            modelBuilder.Entity("SpellItBackend.Models.WordList", b =>
                {
                    b.Property<int>("WordListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OwningUserId")
                        .HasColumnType("int");

                    b.Property<string>("WordListName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WordListId");

                    b.ToTable("WordLists");

                    b.HasData(
                        new
                        {
                            WordListId = 1,
                            OwningUserId = 1,
                            WordListName = "vegetables"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
